server:
  port: 8090

spring:
  datasource:
    # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.101.91:3306/qwz-blog-3?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 配置最大池大小
      maximum-pool-size: 12
      # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 300000
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1200000
      # 从池返回的连接的默认自动提交行为。默认值为true。
      auto-commit: true

logging:
  level:
    com.qinweizhao.blog: DEBUG
  file:
    path: ${blog.work-dir}/log

blog:
  # 例如：https://www.qinweizhao.com
  blog-url: https://www.qinweizhao.com
  theme-dir-name: blog-frontend-portal
  frontend-dir-name: frontend
  auth-enabled: true
  mode: PRODUCTION
  work-dir: ${user.home}/.blog/
  cache: memory
  admin-path: qwz